spring.application.name=smart-logistics
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_logistics
spring.datasource.username=postgres
spring.datasource.password=siddhant

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.indent_output=true
